//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaistrovaControl10.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DepoMaistrovaEntities1 : DbContext
    {
        public DepoMaistrovaEntities1()
            : base("name=DepoMaistrovaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FloorsTable> FloorsTable { get; set; }
        public virtual DbSet<ReportTable> ReportTable { get; set; }
        public virtual DbSet<StatusWorkTable> StatusWorkTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TrolleyTable> TrolleyTable { get; set; }
        public virtual DbSet<TypeWorkTable> TypeWorkTable { get; set; }
        public virtual DbSet<WorkTable> WorkTable { get; set; }
    }
}
