//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaistrovaControl10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTable
    {
        public int IdReport { get; set; }
        public int IdWork { get; set; }
        public int IdTrolly { get; set; }
        public int IdStatus { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
    
        public virtual StatusWorkTable StatusWorkTable { get; set; }
        public virtual TrolleyTable TrolleyTable { get; set; }
        public virtual WorkTable WorkTable { get; set; }
    }
}
