//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaistrovaControl10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkTable()
        {
            this.ReportTable = new HashSet<ReportTable>();
        }
    
        public int PersonalNumberWork { get; set; }
        public int TypeWork { get; set; }
        public string TitleWork { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportTable> ReportTable { get; set; }
        public virtual TypeWorkTable TypeWorkTable { get; set; }
    }
}
